INSERT INTO marca (descricao, fipeid, tipoveiculo) VALUES ('AVELLOZ', '216', 1);
INSERT INTO marca (descricao, fipeid, tipoveiculo) VALUES ('BULL', '212', 1);
INSERT INTO marca (descricao, fipeid, tipoveiculo) VALUES ('CAB MOTORS', '236', 0);
INSERT INTO marca (descricao, fipeid, tipoveiculo) VALUES ('CAOA CHERY', '245', 0);
INSERT INTO marca (descricao, fipeid, tipoveiculo) VALUES ('CAOA CHERY/CHERY', '161', 0);
INSERT INTO marca (descricao, fipeid, tipoveiculo) VALUES ('D2D MOTORS', '241', 0);
INSERT INTO marca (descricao, fipeid, tipoveiculo) VALUES ('DFSK', '246', 0);
INSERT INTO marca (descricao, fipeid, tipoveiculo) VALUES ('FEVER', '249', 0);
INSERT INTO marca (descricao, fipeid, tipoveiculo) VALUES ('FUSCO MOTOSEGURA', '209', 1);
INSERT INTO marca (descricao, fipeid, tipoveiculo) VALUES ('GWM', '240', 0);
INSERT INTO marca (descricao, fipeid, tipoveiculo) VALUES ('NETA', '250', 0);
INSERT INTO marca (descricao, fipeid, tipoveiculo) VALUES ('NIU', '239', 1);
INSERT INTO marca (descricao, fipeid, tipoveiculo) VALUES ('POLARIS', '210', 1);
INSERT INTO marca (descricao, fipeid, tipoveiculo) VALUES ('SERES', '247', 0);
INSERT INTO marca (descricao, fipeid, tipoveiculo) VALUES ('SUPER SOCO', '237', 1);
INSERT INTO marca (descricao, fipeid, tipoveiculo) VALUES ('VENTANE MOTORS', '244', 1);
INSERT INTO marca (descricao, fipeid, tipoveiculo) VALUES ('VOLTZ', '215', 1);
INSERT INTO marca (descricao, fipeid, tipoveiculo) VALUES ('WATTS', '243', 1);
INSERT INTO marca (descricao, fipeid, tipoveiculo) VALUES ('ZONTES', '242', 1);
